//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageAll {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageAll.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn bị tạm khóa, vui lòng đăng nhập sau 1 ngày.
        /// </summary>
        public static string AccountLockout {
            get {
                return ResourceManager.GetString("AccountLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảo mật OTP.
        /// </summary>
        public static string AuthenticatorCode {
            get {
                return ResourceManager.GetString("AuthenticatorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà máy nước không để trống.
        /// </summary>
        public static string CompanyIDInvalid {
            get {
                return ResourceManager.GetString("CompanyIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu và xác nhận lại không khớp.
        /// </summary>
        public static string confirmationnotmatch {
            get {
                return ResourceManager.GetString("confirmationnotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ Email sai định dạng..
        /// </summary>
        public static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thất bại.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đúng số điện thoại.
        /// </summary>
        public static string FormatPhoneNumberFail {
            get {
                return ResourceManager.GetString("FormatPhoneNumberFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy thông tin tài khoản thành công.
        /// </summary>
        public static string GetProfileOK {
            get {
                return ResourceManager.GetString("GetProfileOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản/ email hoặc mật khẩu không đúng..
        /// </summary>
        public static string InvalidCredentialsErrorMessage {
            get {
                return ResourceManager.GetString("InvalidCredentialsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách không để trống.
        /// </summary>
        public static string LinkInvoiceFailCodeEmpty {
            get {
                return ResourceManager.GetString("LinkInvoiceFailCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách đã có liên kết, vui lòng liên hệ công ty..
        /// </summary>
        public static string LinkInvoiceFailCodeHasLink {
            get {
                return ResourceManager.GetString("LinkInvoiceFailCodeHasLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách không có.
        /// </summary>
        public static string LinkInvoiceFailCodeNotExitst {
            get {
                return ResourceManager.GetString("LinkInvoiceFailCodeNotExitst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gán mã khách nhận hóa đơn thành công.
        /// </summary>
        public static string LinkInvoiceSuccess {
            get {
                return ResourceManager.GetString("LinkInvoiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng..
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        public static string ModelStateInValid {
            get {
                return ResourceManager.GetString("ModelStateInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP.
        /// </summary>
        public static string OTPCode {
            get {
                return ResourceManager.GetString("OTPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP không đúng.
        /// </summary>
        public static string OTPInvalid {
            get {
                return ResourceManager.GetString("OTPInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đăng nhập quá nhiều lần bằng OTP trong ngày.
        /// </summary>
        public static string OTPLimited {
            get {
                return ResourceManager.GetString("OTPLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đăng nhập lại sau 3 phút.
        /// </summary>
        public static string OTPWait {
            get {
                return ResourceManager.GetString("OTPWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bắt buộc ít nhất {2} và tối đa {1} ký tự..
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khôi phục.
        /// </summary>
        public static string RecoveryCode {
            get {
                return ResourceManager.GetString("RecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshToken không hợp lệ.
        /// </summary>
        public static string RefreshTokenInvalid {
            get {
                return ResourceManager.GetString("RefreshTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hủy gán mã nhận hóa đơn.
        /// </summary>
        public static string RemoveInvoiceSuccess {
            get {
                return ResourceManager.GetString("RemoveInvoiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo token mới không thành công.
        /// </summary>
        public static string RenewTokenFail {
            get {
                return ResourceManager.GetString("RenewTokenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ bạn chọn không có.
        /// </summary>
        public static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã liên kết công ty nước thành công.
        /// </summary>
        public static string SetCompanyInfoSuccess {
            get {
                return ResourceManager.GetString("SetCompanyInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty không để trống.
        /// </summary>
        public static string SetProfileFailCompanyName {
            get {
                return ResourceManager.GetString("SetProfileFailCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật email không thành công (Email trùng lặp).
        /// </summary>
        public static string SetProfileFailEmail {
            get {
                return ResourceManager.GetString("SetProfileFailEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người đại diện không bỏ trống.
        /// </summary>
        public static string SetProfileFailFullname {
            get {
                return ResourceManager.GetString("SetProfileFailFullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt thông tin cá nhân thành công.
        /// </summary>
        public static string SetProfileSuccess {
            get {
                return ResourceManager.GetString("SetProfileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền truy cập hoặc token hết hạn.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đăng ký được tài khoản, vui lòng kiểm tra số điện thoại hợp lệ.
        /// </summary>
        public static string UserCreateFail {
            get {
                return ResourceManager.GetString("UserCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xác thực tài khoản với OTP.
        /// </summary>
        public static string VerifyOTP {
            get {
                return ResourceManager.GetString("VerifyOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu xác thực.
        /// </summary>
        public static string VerifyPassword {
            get {
                return ResourceManager.GetString("VerifyPassword", resourceCulture);
            }
        }
    }
}
